controller_manager:
  ros__parameters:
    update_rate: 225  # Hz
   
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      ros__parameters:
 
        state_publish_rate: 200.0
       
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints:
          - j0
          - j1
          - j2
          - j3
        command_interfaces:
          - position
        state_interfaces:
          - position
          - velocity
        allow_partial_joints_goal: true
        allow_integration_in_goal_trajectories: true
        constraints:
          stopped_velocity_tolerance: 0.01
          goal_time: 0.0
 
    position_controller:
      type: position_controllers/JointGroupPositionController
      ros__parameters:
        joints:
          - j0
          - j1
          - j2
          - j3
        command_interfaces:
          - position
        state_interfaces:
          - position
          - velocity
 